# Generated by Django 5.0.3 on 2024-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='passwod',
            field=models.IntegerField(),
        ),
    ]
