# Generated by Django 5.0.3 on 2024-04-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addaccount', '0003_remove_accounts_dob_remove_accounts_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='passwod',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='accounts',
            name='post',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
