# Generated by Django 5.0.3 on 2024-04-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addaccount', '0005_alter_accounts_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='passwod',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='post',
            field=models.CharField(max_length=50),
        ),
    ]
